<a href="https://colab.research.google.com/github/Dhanasree-Rajamani/Data-Mining/blob/main/Data%20Mining%20Assignment%205/Random_Projections.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **LSH Random Projections**

Number of Hyperplanes and Binary values to Produce, Vector Dimensions

In [ ]:
nbits = 3
d = 2

3 Hyperplanes with 2 dimensions created

In [ ]:
import numpy as np

plane_norms = np.random.rand(nbits, d) - .5
plane_norms

array([[-0.26137354, -0.3944215 ],
       [ 0.34917003, -0.35894149],
       [-0.42060387,  0.2745561 ]])

Input values

In [ ]:
a = np.asarray([3, 1])
b = np.asarray([2, 1])
c = np.asarray([3, 4])

Calculate dot product

In [ ]:
a_dot = np.dot(a, plane_norms.T)
b_dot = np.dot(b, plane_norms.T)
c_dot = np.dot(c, plane_norms.T)
a_dot

array([-1.17854213,  0.6885686 , -0.98725552])

Separating values in hyperplane 

positive dot product -> Positive side of hyperplane

negative dot product -> Negative side of hyperplane

In [ ]:
a_dot = a_dot > 0
b_dot = b_dot > 0
c_dot = c_dot > 0
a_dot

array([False,  True, False])

Convert boolean array to int

In [ ]:
a_dot = a_dot.astype(int)
b_dot = b_dot.astype(int)
c_dot = c_dot.astype(int)

In [ ]:
a_dot

array([0, 1, 0])

In [ ]:
b_dot

array([0, 1, 0])

In [ ]:
c_dot

array([0, 0, 0])

Convert array to string, create bucket and add vector position to bucket


In [ ]:
vectors = [a_dot, b_dot, c_dot]
buckets = {}
i = 0

for i in range(len(vectors)):
    hash_str = ''.join(vectors[i].astype(str))
    if hash_str not in buckets.keys():
        buckets[hash_str] = []
    buckets[hash_str].append(i)

In [ ]:
print(buckets)

{'010': [0, 1], '000': [2]}
